services:
  capuzzella:
    build:
      context: .
      dockerfile: container/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    user: "1000:1000"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./drafts:/app/drafts
    restart: unless-stopped
